"""Gera o Problem.h (C++20) e os artefatos de dados a partir da tabela de simbolos tipada.

Este modulo:
1. Percorre a AST + tabela de tipos -> emite o texto C++20 do Problem.h
2. Serializa os dados da instancia (self.*) -> instance.rko-data
3. Salva tudo no disco (Problem.h, instance.rko-data, manifesto, etc.)
"""

from __future__ import annotations

import ast
from hashlib import sha256
import json
from pathlib import Path
from typing import Any

from .model import CompilationArtifact, EnvironmentIR, FunctionIR, LANGUAGE_VERSION, NativeCompileError, NativeType, Diagnostic

def cpp_name(name: str) -> str:
    rendered = "".join(
        character
        if character.isascii() and (character.isalnum() or character == "_")
        else "_"
        for character in name
    )
    if not rendered:
        rendered = "value"
    # Prefix every source-level identifier so it cannot collide with injected
    # context names, C++ keywords or backend temporaries.
    return f"rko_user_{rendered}"


class CppEmitter:
    def __init__(self, ir: EnvironmentIR):
        self.ir = ir
        self.fields = {field.name: field.type for field in ir.data_fields}
        self.current: FunctionIR | None = None
        self._unique_counter = 0

    def cpp_type(self, type_info: NativeType) -> str:
        if type_info.kind == "bool":
            return "bool"
        if type_info.kind == "int64":
            return "std::int64_t"
        if type_info.kind == "float64":
            return "double"
        if type_info.kind == "none":
            return "void"
        if type_info.kind == "list" and type_info.item is not None:
            return f"std::vector<{self.cpp_type(type_info.item)}>"
        if type_info.kind == "tuple":
            return f"std::tuple<{', '.join(self.cpp_type(item) for item in type_info.items)}>"
        raise NativeCompileError(
            Diagnostic("RKO-NATIVE-CPP-001", f"no C++ type for {type_info.display()}")
        )

    def render(self) -> str:
        field_lines = []
        for field in self.ir.data_fields:
            field_type = "int" if field.name == "tam_solution" else self.cpp_type(field.type)
            field_lines.append(f"    {field_type} {field.cpp_name}{{}};")

        prototypes: list[str] = []
        definitions: list[str] = []
        for name in self.ir.function_order:
            function = self.ir.functions[name]
            prototypes.append(self.signature(function) + ";")
        for name in self.ir.function_order:
            definitions.extend(self.function(self.ir.functions[name]))

        read_fields = [
            f"    RkoNativeRead(input, data.{field.cpp_name});"
            for field in self.ir.data_fields
        ]

        lines = [
            "// Generated by RKO Native Language V1. Do not edit.",
            "#ifndef RKO_NATIVE_V1_PROBLEM_H",
            "#define RKO_NATIVE_V1_PROBLEM_H",
            "",
            "#include <algorithm>",
            "#include <array>",
            "#include <charconv>",
            "#include <cmath>",
            "#include <cstddef>",
            "#include <cstdint>",
            "#include <cstdio>",
            "#include <cstdlib>",
            "#include <fstream>",
            "#include <limits>",
            "#include <numeric>",
            "#include <stdexcept>",
            "#include <string>",
            "#include <system_error>",
            "#include <tuple>",
            "#include <type_traits>",
            "#include <utility>",
            "#include <vector>",
            "",
            "struct TProblemData",
            "{",
            *field_lines,
            "};",
            "",
            *self.runtime_support(),
            "",
            "void ReadData(char name[], TProblemData& data)",
            "{",
            "    std::ifstream input(name, std::ios::binary);",
            "    if (!input) {",
            "        std::fprintf(stderr, \"Unable to open native RKO data: %s\\n\", name);",
            "        std::exit(2);",
            "    }",
            "    std::string magic;",
            "    input >> magic;",
            "    if (magic != \"RKO_NATIVE_DATA_V1\") {",
            "        std::fprintf(stderr, \"Invalid RKO Native V1 data file\\n\");",
            "        std::exit(2);",
            "    }",
            *read_fields,
            "    input >> std::ws;",
            "    if (!input.eof()) {",
            "        std::fprintf(stderr, \"Unexpected trailing native data tokens\\n\");",
            "        std::exit(2);",
            "    }",
            "    if (data.n <= 0) {",
            "        std::fprintf(stderr, \"Invalid native solution dimension\\n\");",
            "        std::exit(2);",
            "    }",
            "}",
            "",
            *prototypes,
            "",
            *definitions,
            "double Decoder(TSol& s, const TProblemData& data)",
            "{",
            "    if (s.rk.size() != static_cast<std::size_t>(data.n))",
            "        throw std::invalid_argument(\"random-key vector length does not match tam_solution\");",
            f"    const auto decoded = {self.ir.functions['decoder'].cpp_name}(s.rk, data);",
            f"    return {self.ir.functions['cost'].cpp_name}(decoded, false, data);",
            "}",
            "",
            "void FreeMemoryProblem(TProblemData&) {}",
            "",
            "#endif",
            "",
        ]
        return "\n".join(lines)

    def runtime_support(self) -> list[str]:
        return [
            "template <typename T>",
            "static void RkoNativeRead(std::istream& input, T& value)",
            "{",
            "    input >> value;",
            "    if (!input) throw std::runtime_error(\"invalid native data token\");",
            "}",
            "",
            "static void RkoNativeRead(std::istream& input, bool& value)",
            "{",
            "    int token = 0;",
            "    input >> token;",
            "    if (!input || (token != 0 && token != 1)) throw std::runtime_error(\"invalid bool token\");",
            "    value = token != 0;",
            "}",
            "",
            "template <typename T>",
            "static void RkoNativeRead(std::istream& input, std::vector<T>& values);",
            "",
            "template <typename... T>",
            "static void RkoNativeRead(std::istream& input, std::tuple<T...>& value);",
            "",
            "template <typename T>",
            "static void RkoNativeRead(std::istream& input, std::vector<T>& values)",
            "{",
            "    std::size_t size = 0;",
            "    input >> size;",
            "    if (!input) throw std::runtime_error(\"invalid vector length\");",
            "    values.resize(size);",
            "    for (std::size_t index = 0; index < size; ++index) RkoNativeRead(input, values[index]);",
            "}",
            "",
            "static void RkoNativeRead(std::istream& input, std::vector<bool>& values)",
            "{",
            "    std::size_t size = 0;",
            "    input >> size;",
            "    if (!input) throw std::runtime_error(\"invalid bool vector length\");",
            "    values.resize(size);",
            "    for (std::size_t index = 0; index < size; ++index) {",
            "        bool value = false; RkoNativeRead(input, value); values[index] = value;",
            "    }",
            "}",
            "",
            "template <typename Tuple, std::size_t... Indices>",
            "static void RkoNativeReadTuple(std::istream& input, Tuple& value, std::index_sequence<Indices...>)",
            "{",
            "    (RkoNativeRead(input, std::get<Indices>(value)), ...);",
            "}",
            "",
            "template <typename... T>",
            "static void RkoNativeRead(std::istream& input, std::tuple<T...>& value)",
            "{",
            "    RkoNativeReadTuple(input, value, std::index_sequence_for<T...>{});",
            "}",
            "",
            "static std::size_t RkoNativeIndex(std::int64_t index, std::size_t size)",
            "{",
            "    const std::int64_t normalized = index < 0 ? index + static_cast<std::int64_t>(size) : index;",
            "    if (normalized < 0 || normalized >= static_cast<std::int64_t>(size))",
            "        throw std::out_of_range(\"RKO Native V1 index out of range\");",
            "    return static_cast<std::size_t>(normalized);",
            "}",
            "",
            "template <typename T>",
            "static decltype(auto) RkoNativeAt(const std::vector<T>& values, std::int64_t index)",
            "{ return values[RkoNativeIndex(index, values.size())]; }",
            "",
            "template <typename T>",
            "static decltype(auto) RkoNativeAt(std::vector<T>& values, std::int64_t index)",
            "{ return values[RkoNativeIndex(index, values.size())]; }",
            "",
            "template <typename T>",
            "static std::vector<T> RkoNativeRepeat(const T& value, std::int64_t count)",
            "{",
            "    if (count < 0) count = 0;",
            "    return std::vector<T>(static_cast<std::size_t>(count), value);",
            "}",
            "",
            "template <typename T>",
            "static std::vector<T> RkoNativeSlice(const std::vector<T>& values, std::int64_t start, std::int64_t stop)",
            "{",
            "    const auto size = static_cast<std::int64_t>(values.size());",
            "    if (start < 0) start += size;",
            "    if (stop < 0) stop += size;",
            "    start = std::max<std::int64_t>(0, std::min(start, size));",
            "    stop = std::max<std::int64_t>(0, std::min(stop, size));",
            "    if (stop < start) stop = start;",
            "    return std::vector<T>(values.begin() + start, values.begin() + stop);",
            "}",
            "",
            "template <typename T>",
            "static T RkoNativePop(std::vector<T>& values, std::int64_t index = -1)",
            "{",
            "    const auto position = RkoNativeIndex(index, values.size());",
            "    T result = values[position];",
            "    values.erase(values.begin() + static_cast<std::ptrdiff_t>(position));",
            "    return result;",
            "}",
            "",
            "template <typename Left, typename Right>",
            "static double RkoNativeTrueDiv(Left left, Right right)",
            "{",
            "    const double denominator = static_cast<double>(right);",
            "    if (denominator == 0.0) throw std::domain_error(\"division by zero\");",
            "    const double result = static_cast<double>(left) / denominator;",
            "    if (!std::isfinite(result)) throw std::overflow_error(\"non-finite V1 division result\");",
            "    return result;",
            "}",
            "",
            "static std::int64_t RkoNativeFloorDivIntegers(std::int64_t left, std::int64_t right)",
            "{",
            "    if (right == 0) throw std::domain_error(\"integer division by zero\");",
            "    if (left == std::numeric_limits<std::int64_t>::min() && right == -1)",
            "        throw std::overflow_error(\"integer floor division overflow\");",
            "    auto quotient = left / right; auto remainder = left % right;",
            "    if (remainder != 0 && ((remainder < 0) != (right < 0))) --quotient;",
            "    return quotient;",
            "}",
            "",
            "static std::pair<double, double> RkoNativeFloatDivMod(double left, double right)",
            "{",
            "    if (!std::isfinite(left) || !std::isfinite(right))",
            "        throw std::domain_error(\"float divmod requires finite operands\");",
            "    if (right == 0.0) throw std::domain_error(\"float division by zero\");",
            "    double modulo = std::fmod(left, right);",
            "    double division = (left - modulo) / right;",
            "    if (modulo != 0.0) {",
            "        if ((right < 0.0) != (modulo < 0.0)) {",
            "            modulo += right;",
            "            division -= 1.0;",
            "        }",
            "    } else {",
            "        modulo = std::copysign(0.0, right);",
            "    }",
            "    double quotient = 0.0;",
            "    if (division != 0.0) {",
            "        quotient = std::floor(division);",
            "        if (division - quotient > 0.5) quotient += 1.0;",
            "    } else {",
            "        quotient = std::copysign(0.0, left / right);",
            "    }",
            "    if (!std::isfinite(quotient) || !std::isfinite(modulo))",
            "        throw std::overflow_error(\"non-finite float divmod result\");",
            "    return {quotient, modulo};",
            "}",
            "",
            "template <typename Left, typename Right>",
            "static auto RkoNativeFloorDiv(Left left, Right right)",
            "{",
            "    if constexpr (std::is_integral_v<Left> && std::is_integral_v<Right>)",
            "        return RkoNativeFloorDivIntegers(static_cast<std::int64_t>(left), static_cast<std::int64_t>(right));",
            "    else",
            "        return RkoNativeFloatDivMod(static_cast<double>(left), static_cast<double>(right)).first;",
            "}",
            "",
            "template <typename Left, typename Right>",
            "static auto RkoNativeModulo(Left left, Right right)",
            "{",
            "    if constexpr (std::is_integral_v<Left> && std::is_integral_v<Right>) {",
            "        const auto lhs = static_cast<std::int64_t>(left);",
            "        const auto rhs = static_cast<std::int64_t>(right);",
            "        if (rhs == 0) throw std::domain_error(\"integer modulo by zero\");",
            "        if (lhs == std::numeric_limits<std::int64_t>::min() && rhs == -1) return std::int64_t{0};",
            "        auto remainder = lhs % rhs;",
            "        if (remainder != 0 && ((remainder < 0) != (rhs < 0))) remainder += rhs;",
            "        return remainder;",
            "    } else {",
            "        return RkoNativeFloatDivMod(static_cast<double>(left), static_cast<double>(right)).second;",
            "    }",
            "}",
            "",
            "template <typename Left, typename Right>",
            "static auto RkoNativeMin(Left left, Right right) -> std::common_type_t<Left, Right>",
            "{ using Result = std::common_type_t<Left, Right>; return std::min<Result>(left, right); }",
            "",
            "template <typename Left, typename Right>",
            "static auto RkoNativeMax(Left left, Right right) -> std::common_type_t<Left, Right>",
            "{ using Result = std::common_type_t<Left, Right>; return std::max<Result>(left, right); }",
            "",
            "template <typename T>",
            "static std::int64_t RkoNativeToInt(T value)",
            "{",
            "    if constexpr (std::is_integral_v<T>) {",
            "        return static_cast<std::int64_t>(value);",
            "    } else {",
            "        const double numeric = static_cast<double>(value);",
            "        if (!std::isfinite(numeric) || numeric < -9223372036854775808.0 || numeric >= 9223372036854775808.0)",
            "            throw std::overflow_error(\"V1 int conversion exceeds int64\");",
            "        return static_cast<std::int64_t>(numeric);",
            "    }",
            "}",
            "",
            "static std::int64_t RkoNativeAbs(std::int64_t value)",
            "{",
            "    if (value == std::numeric_limits<std::int64_t>::min())",
            "        throw std::overflow_error(\"V1 abs result exceeds int64\");",
            "    return value < 0 ? -value : value;",
            "}",
            "",
            "static double RkoNativeAbs(double value)",
            "{ return std::abs(value); }",
            "",
            "static double RkoNativeMathResult(double result)",
            "{",
            "    if (!std::isfinite(result)) throw std::domain_error(\"non-finite V1 math result\");",
            "    return result;",
            "}",
            "",
            "static double RkoNativeSqrt(double value)",
            "{",
            "    if (value < 0.0) throw std::domain_error(\"math.sqrt domain error\");",
            "    return RkoNativeMathResult(std::sqrt(value));",
            "}",
            "",
            "static double RkoNativeLog(double value)",
            "{",
            "    if (value <= 0.0) throw std::domain_error(\"math.log domain error\");",
            "    return RkoNativeMathResult(std::log(value));",
            "}",
            "",
            "static double RkoNativeExp(double value)",
            "{ return RkoNativeMathResult(std::exp(value)); }",
            "",
            "static double RkoNativeSin(double value)",
            "{ return RkoNativeMathResult(std::sin(value)); }",
            "",
            "static double RkoNativeCos(double value)",
            "{ return RkoNativeMathResult(std::cos(value)); }",
            "",
            "static double RkoNativeTan(double value)",
            "{ return RkoNativeMathResult(std::tan(value)); }",
            "",
            "template <typename T>",
            "static std::int64_t RkoNativeFloor(T value)",
            "{",
            "    if constexpr (std::is_integral_v<T>) return RkoNativeToInt(value);",
            "    else return RkoNativeToInt(std::floor(static_cast<double>(value)));",
            "}",
            "",
            "template <typename T>",
            "static std::int64_t RkoNativeCeil(T value)",
            "{",
            "    if constexpr (std::is_integral_v<T>) return RkoNativeToInt(value);",
            "    else return RkoNativeToInt(std::ceil(static_cast<double>(value)));",
            "}",
            "",
            "static double RkoNativeRound(double value, std::int64_t digits)",
            "{",
            "    if (!std::isfinite(value)) throw std::domain_error(\"RKO Native V1 round requires a finite value\");",
            "    if (digits < 0) throw std::domain_error(\"RKO Native V1 round requires non-negative ndigits\");",
            "    if (digits > 400) return value;",
            "    std::array<char, 1200> buffer{};",
            "    const auto rendered = std::to_chars(buffer.data(), buffer.data() + buffer.size(), value,",
            "                                        std::chars_format::fixed, static_cast<int>(digits));",
            "    if (rendered.ec != std::errc{}) throw std::runtime_error(\"unable to render Python-compatible round\");",
            "    double result = 0.0;",
            "    const auto parsed = std::from_chars(buffer.data(), rendered.ptr, result, std::chars_format::fixed);",
            "    if (parsed.ec != std::errc{} || parsed.ptr != rendered.ptr)",
            "        throw std::runtime_error(\"unable to parse Python-compatible round\");",
            "    return result;",
            "}",
            "",
            "static std::int64_t RkoNativeRoundInt(double value)",
            "{",
            "    if (!std::isfinite(value)) throw std::domain_error(\"RKO Native V1 round requires a finite value\");",
            "    char buffer[768];",
            "    const auto rendered = std::to_chars(buffer, buffer + sizeof(buffer), value, std::chars_format::fixed, 0);",
            "    if (rendered.ec != std::errc{}) throw std::runtime_error(\"unable to render integer round\");",
            "    std::int64_t result = 0;",
            "    const auto parsed = std::from_chars(buffer, rendered.ptr, result);",
            "    if (parsed.ec == std::errc::result_out_of_range)",
            "        throw std::overflow_error(\"RKO Native V1 round result exceeds int64\");",
            "    if (parsed.ec != std::errc{} || parsed.ptr != rendered.ptr)",
            "        throw std::runtime_error(\"unable to parse integer round\");",
            "    return result;",
            "}",
            "",
            "static std::vector<std::int64_t> RkoNativeStableArgsort(const std::vector<double>& values)",
            "{",
            "    for (double value : values)",
            "        if (!std::isfinite(value)) throw std::domain_error(\"RKO Native V1 argsort requires finite keys\");",
            "    std::vector<std::int64_t> indices(values.size());",
            "    std::iota(indices.begin(), indices.end(), 0);",
            "    std::stable_sort(indices.begin(), indices.end(), [&](std::int64_t left, std::int64_t right) {",
            "        const double lhs = values[static_cast<std::size_t>(left)];",
            "        const double rhs = values[static_cast<std::size_t>(right)];",
            "        return lhs < rhs;",
            "    });",
            "    return indices;",
            "}",
        ]

    def signature(self, function: FunctionIR) -> str:
        parameters: list[str] = []
        for parameter in function.parameters:
            rendered_type = self.cpp_type(parameter.type)
            if parameter.type.kind in {"list", "tuple"}:
                reference = "&" if parameter.mutated else "const " + rendered_type + "&"
                if parameter.mutated:
                    rendered = f"{rendered_type}&"
                else:
                    rendered = reference
            else:
                rendered = rendered_type
            parameters.append(f"{rendered} {cpp_name(parameter.name)}")
        parameters.append("const TProblemData& data")
        return f"static {self.cpp_type(function.return_type)} {function.cpp_name}({', '.join(parameters)})"

    def function(self, function: FunctionIR) -> list[str]:
        self.current = function
        parameter_names = {parameter.name for parameter in function.parameters}
        local_declarations: list[str] = []
        for name, type_info in sorted(function.local_types.items()):
            if name in parameter_names or name in function.loop_targets:
                continue
            local_declarations.append(f"    {self.cpp_type(type_info)} {cpp_name(name)}{{}};")
        lines = [self.signature(function), "{"]
        lines.extend(local_declarations)
        if local_declarations:
            lines.append("")
        lines.extend(self.block(function.node.body, 1))
        lines.extend(["}", ""])
        self.current = None
        return lines

    def block(self, statements: list[ast.stmt], indent: int) -> list[str]:
        result: list[str] = []
        for statement in statements:
            result.extend(self.statement(statement, indent))
        return result

    def statement(self, node: ast.stmt, indent: int) -> list[str]:
        prefix = "    " * indent
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            return []
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            value = "{}" if isinstance(node.value, ast.List) and not node.value.elts else self.expression(node.value)
            return [f"{prefix}{self.target(node.targets[0])} = {value};"]
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            if node.value is None:
                return []
            value = "{}" if isinstance(node.value, ast.List) and not node.value.elts else self.expression(node.value)
            return [f"{prefix}{cpp_name(node.target.id)} = {value};"]
        if isinstance(node, ast.AugAssign):
            target = self.target(node.target)
            value = self.expression(node.value)
            if isinstance(node.op, ast.Mod):
                return [f"{prefix}{target} = RkoNativeModulo({target}, {value});"]
            if isinstance(node.op, ast.FloorDiv):
                return [f"{prefix}{target} = RkoNativeFloorDiv({target}, {value});"]
            if isinstance(node.op, ast.Div):
                return [f"{prefix}{target} = RkoNativeTrueDiv({target}, {value});"]
            operator = {ast.Add: "+=", ast.Sub: "-=", ast.Mult: "*="}.get(type(node.op))
            if operator is None:
                raise AssertionError(f"unhandled augmented operator {type(node.op).__name__}")
            return [f"{prefix}{target} {operator} {value};"]
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Call):
            return [f"{prefix}{self.expression(node.value)};"]
        if isinstance(node, ast.If):
            lines = [f"{prefix}if ({self.expression(node.test)}) {{"]
            lines.extend(self.block(node.body, indent + 1))
            if node.orelse:
                lines.append(f"{prefix}}} else {{")
                lines.extend(self.block(node.orelse, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        if isinstance(node, ast.While):
            lines = [f"{prefix}while ({self.expression(node.test)}) {{"]
            lines.extend(self.block(node.body, indent + 1))
            lines.append(f"{prefix}}}")
            return lines
        if isinstance(node, ast.For):
            return self.for_loop(node, indent)
        if isinstance(node, ast.Return):
            if node.value is None:
                return [f"{prefix}return;"]
            return [f"{prefix}return {self.expression(node.value)};"]
        if isinstance(node, ast.Break):
            return [f"{prefix}break;"]
        if isinstance(node, ast.Continue):
            return [f"{prefix}continue;"]
        if isinstance(node, ast.Pass):
            return []
        raise AssertionError(f"unhandled statement {type(node).__name__}")

    def for_loop(self, node: ast.For, indent: int) -> list[str]:
        prefix = "    " * indent
        if isinstance(node.iter, ast.Call) and isinstance(node.iter.func, ast.Name) and node.iter.func.id == "range":
            args = node.iter.args
            if len(args) == 1:
                start, stop, step = "0", self.expression(args[0]), "1"
            elif len(args) == 2:
                start, stop, step = self.expression(args[0]), self.expression(args[1]), "1"
            else:
                start, stop, step = (self.expression(argument) for argument in args)
            target = cpp_name(node.target.id) if isinstance(node.target, ast.Name) else "rko_invalid"
            start_name = self.unique("range_start")
            stop_name = self.unique("range_stop")
            step_name = self.unique("range_step")
            lines = [
                f"{prefix}const std::int64_t {start_name} = {start};",
                f"{prefix}const std::int64_t {stop_name} = {stop};",
                f"{prefix}const std::int64_t {step_name} = {step};",
                f"{prefix}for (std::int64_t {target} = {start_name}; "
                f"({step_name} > 0 ? {target} < {stop_name} : {target} > {stop_name}); "
                f"{target} += {step_name}) {{"
            ]
            lines.extend(self.block(node.body, indent + 1))
            lines.append(f"{prefix}}}")
            return lines

        if isinstance(node.iter, ast.Call) and isinstance(node.iter.func, ast.Name) and node.iter.func.id == "enumerate":
            container = self.expression(node.iter.args[0])
            unique = self.unique("enumerate")
            values_name = self.unique("enumerate_values")
            if not isinstance(node.target, ast.Tuple) or len(node.target.elts) != 2:
                raise AssertionError("typed frontend accepted invalid enumerate target")
            index_target = cpp_name(node.target.elts[0].id)
            item_target = cpp_name(node.target.elts[1].id)
            lines = [
                f"{prefix}const auto {values_name} = {container};",
                f"{prefix}for (std::size_t {unique} = 0; {unique} < {values_name}.size(); ++{unique}) {{",
                f"{prefix}    const std::int64_t {index_target} = static_cast<std::int64_t>({unique});",
                f"{prefix}    const auto {item_target} = {values_name}[{unique}];",
            ]
            lines.extend(self.block(node.body, indent + 1))
            lines.append(f"{prefix}}}")
            return lines

        iterable = self.expression(node.iter)
        if not isinstance(node.target, ast.Name):
            raise AssertionError("typed frontend accepted invalid direct loop target")
        target = cpp_name(node.target.id)
        values_name = self.unique("iterable_values")
        lines = [
            f"{prefix}const auto {values_name} = {iterable};",
            f"{prefix}for (const auto {target} : {values_name}) {{",
        ]
        lines.extend(self.block(node.body, indent + 1))
        lines.append(f"{prefix}}}")
        return lines

    def target(self, node: ast.expr) -> str:
        if isinstance(node, ast.Name):
            return cpp_name(node.id)
        if isinstance(node, ast.Subscript):
            if isinstance(node.slice, ast.Slice):
                raise AssertionError("slice assignment is outside V1")
            return f"RkoNativeAt({self.expression(node.value)}, {self.expression(node.slice)})"
        raise AssertionError(f"unhandled target {type(node).__name__}")

    def expression(self, node: ast.expr) -> str:
        if isinstance(node, ast.Constant):
            if node.value is True:
                return "true"
            if node.value is False:
                return "false"
            if node.value is None:
                return "nullptr"
            if isinstance(node.value, float):
                return repr(node.value)
            if isinstance(node.value, int):
                return str(node.value)
            raise AssertionError(f"unhandled constant {node.value!r}")
        if isinstance(node, ast.Name):
            return cpp_name(node.id)
        if isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name) and node.value.id == "self":
            field = next(field for field in self.ir.data_fields if field.name == node.attr)
            return f"data.{field.cpp_name}"
        if isinstance(node, ast.List):
            type_info = self.type_of(node)
            return f"{self.cpp_type(type_info)}{{{', '.join(self.expression(element) for element in node.elts)}}}"
        if isinstance(node, ast.Tuple):
            return f"std::make_tuple({', '.join(self.expression(element) for element in node.elts)})"
        if isinstance(node, ast.ListComp):
            generator = node.generators[0]
            assert isinstance(generator.target, ast.Name)
            iterable = self.expression(generator.iter)
            result_type = self.type_of(node)
            result_name = self.unique("listcomp")
            values_name = self.unique("listcomp_values")
            target_name = cpp_name(generator.target.id)
            return (
                "([&]() { "
                f"{self.cpp_type(result_type)} {result_name}; "
                f"const auto {values_name} = {iterable}; "
                f"{result_name}.reserve({values_name}.size()); "
                f"for (const auto {target_name} : {values_name}) {{ "
                f"{result_name}.push_back({self.expression(node.elt)}); "
                "} "
                f"return {result_name}; "
                "}())"
            )
        if isinstance(node, ast.Subscript):
            container_type = self.type_of(node.value)
            if isinstance(node.slice, ast.Slice):
                size = f"static_cast<std::int64_t>(({self.expression(node.value)}).size())"
                start = self.expression(node.slice.lower) if node.slice.lower is not None else "0"
                stop = self.expression(node.slice.upper) if node.slice.upper is not None else size
                return f"RkoNativeSlice({self.expression(node.value)}, {start}, {stop})"
            if container_type.kind == "tuple" and isinstance(node.slice, ast.Constant):
                index = node.slice.value
                normalized = index if index >= 0 else len(container_type.items) + index
                return f"std::get<{normalized}>({self.expression(node.value)})"
            return f"RkoNativeAt({self.expression(node.value)}, {self.expression(node.slice)})"
        if isinstance(node, ast.BinOp):
            if isinstance(node.op, ast.Mult) and isinstance(node.left, ast.List) and len(node.left.elts) == 1:
                item_type = self.type_of(node.left).item
                assert item_type is not None
                return f"RkoNativeRepeat<{self.cpp_type(item_type)}>({self.expression(node.left.elts[0])}, {self.expression(node.right)})"
            left, right = self.expression(node.left), self.expression(node.right)
            if isinstance(node.op, ast.Div):
                return f"RkoNativeTrueDiv({left}, {right})"
            if isinstance(node.op, ast.FloorDiv):
                return f"RkoNativeFloorDiv({left}, {right})"
            if isinstance(node.op, ast.Mod):
                return f"RkoNativeModulo({left}, {right})"
            operator = {ast.Add: "+", ast.Sub: "-", ast.Mult: "*"}[type(node.op)]
            return f"({left} {operator} {right})"
        if isinstance(node, ast.UnaryOp):
            if (
                isinstance(node.op, ast.USub)
                and isinstance(node.operand, ast.Constant)
                and node.operand.value == 2**63
            ):
                return "std::numeric_limits<std::int64_t>::min()"
            operator = {ast.Not: "!", ast.UAdd: "+", ast.USub: "-"}[type(node.op)]
            return f"({operator}{self.expression(node.operand)})"
        if isinstance(node, ast.BoolOp):
            operator = " && " if isinstance(node.op, ast.And) else " || "
            return "(" + operator.join(self.expression(value) for value in node.values) + ")"
        if isinstance(node, ast.Compare):
            left_nodes = [node.left, *node.comparators[:-1]]
            right_nodes = node.comparators
            operators = [
                {ast.Eq: "==", ast.NotEq: "!=", ast.Lt: "<", ast.LtE: "<=", ast.Gt: ">", ast.GtE: ">="}[type(operator)]
                for operator in node.ops
            ]
            comparisons = [
                f"({self.expression(left)} {operator} {self.expression(right)})"
                for left, operator, right in zip(left_nodes, operators, right_nodes)
            ]
            return "(" + " && ".join(comparisons) + ")"
        if isinstance(node, ast.IfExp):
            return f"({self.expression(node.test)} ? {self.expression(node.body)} : {self.expression(node.orelse)})"
        if isinstance(node, ast.Call):
            return self.call(node)
        raise AssertionError(f"unhandled expression {type(node).__name__}")

    def call(self, node: ast.Call) -> str:
        if (
            isinstance(node.func, ast.Attribute)
            and node.func.attr == "tolist"
            and isinstance(node.func.value, ast.Call)
        ):
            return self.call(node.func.value)
        if isinstance(node.func, ast.Attribute) and isinstance(node.func.value, ast.Name) and node.func.value.id == "self":
            function = self.ir.functions[node.func.attr]
            arguments = [self.expression(argument) for argument in node.args]
            arguments.append("data")
            return f"{function.cpp_name}({', '.join(arguments)})"
        canonical = self.canonical_name(node.func)
        if canonical == "numpy.argsort":
            return f"RkoNativeStableArgsort({self.expression(node.args[0])})"
        if isinstance(node.func, ast.Name):
            name = node.func.id
            if name == "len":
                return f"static_cast<std::int64_t>(({self.expression(node.args[0])}).size())"
            if name == "float":
                return f"static_cast<double>({self.expression(node.args[0])})"
            if name == "int":
                return f"RkoNativeToInt({self.expression(node.args[0])})"
            if name == "bool":
                return f"static_cast<bool>({self.expression(node.args[0])})"
            if name == "min":
                return f"RkoNativeMin({self.expression(node.args[0])}, {self.expression(node.args[1])})"
            if name == "max":
                return f"RkoNativeMax({self.expression(node.args[0])}, {self.expression(node.args[1])})"
            if name == "round":
                if len(node.args) == 1:
                    return f"RkoNativeRoundInt({self.expression(node.args[0])})"
                return f"RkoNativeRound({self.expression(node.args[0])}, {self.expression(node.args[1])})"
            if name == "abs":
                return f"RkoNativeAbs({self.expression(node.args[0])})"
        if canonical and canonical.startswith("math."):
            function = canonical.split(".", 1)[1]
            native_function = {
                "sqrt": "RkoNativeSqrt",
                "exp": "RkoNativeExp",
                "log": "RkoNativeLog",
                "sin": "RkoNativeSin",
                "cos": "RkoNativeCos",
                "tan": "RkoNativeTan",
                "floor": "RkoNativeFloor",
                "ceil": "RkoNativeCeil",
            }[function]
            return f"{native_function}({self.expression(node.args[0])})"
        if isinstance(node.func, ast.Attribute):
            owner = self.expression(node.func.value)
            if node.func.attr == "copy":
                return owner
            if node.func.attr == "append":
                return f"({owner}).push_back({self.expression(node.args[0])})"
            if node.func.attr == "pop":
                index = self.expression(node.args[0]) if node.args else "-1"
                return f"RkoNativePop({owner}, {index})"
        raise AssertionError(f"unhandled call {ast.unparse(node.func)}")

    def canonical_name(self, node: ast.expr) -> str | None:
        if isinstance(node, ast.Name):
            return self.ir.import_aliases.get(node.id, node.id)
        if isinstance(node, ast.Attribute):
            parent = self.canonical_name(node.value)
            return f"{parent}.{node.attr}" if parent else None
        return None

    def type_of(self, node: ast.expr) -> NativeType:
        assert self.current is not None
        if isinstance(node, ast.Constant):
            if isinstance(node.value, bool): return NativeType.bool()
            if isinstance(node.value, int): return NativeType.int()
            if isinstance(node.value, float): return NativeType.float()
            if node.value is None: return NativeType.none()
        if isinstance(node, ast.Name):
            return self.current.local_types[node.id]
        if isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name) and node.value.id == "self":
            return self.fields[node.attr]
        if isinstance(node, ast.List):
            if node.elts:
                return NativeType.list(self.type_of(node.elts[0]))
            return self.current.empty_list_types[id(node)]
        if isinstance(node, ast.Tuple):
            return NativeType.tuple(tuple(self.type_of(element) for element in node.elts))
        if isinstance(node, ast.ListComp):
            return NativeType.list(self.type_of(node.elt))
        if isinstance(node, ast.Subscript):
            container = self.type_of(node.value)
            if isinstance(node.slice, ast.Slice): return container
            if container.kind == "list" and container.item is not None: return container.item
            if container.kind == "tuple" and isinstance(node.slice, ast.Constant):
                index = node.slice.value
                normalized = index if index >= 0 else len(container.items) + index
                return container.items[normalized]
        if isinstance(node, ast.BinOp):
            if isinstance(node.op, ast.Mult) and self.type_of(node.left).kind == "list": return self.type_of(node.left)
            if isinstance(node.op, ast.Div): return NativeType.float()
            left, right = self.type_of(node.left), self.type_of(node.right)
            return NativeType.float() if NativeType.float() in {left, right} else NativeType.int()
        if isinstance(node, ast.UnaryOp):
            return NativeType.bool() if isinstance(node.op, ast.Not) else self.type_of(node.operand)
        if isinstance(node, (ast.BoolOp, ast.Compare)): return NativeType.bool()
        if isinstance(node, ast.IfExp):
            left, right = self.type_of(node.body), self.type_of(node.orelse)
            return left if left == right else NativeType.float()
        if isinstance(node, ast.Call):
            if isinstance(node.func, ast.Attribute) and node.func.attr == "tolist" and isinstance(node.func.value, ast.Call):
                return self.type_of(node.func.value)
            if isinstance(node.func, ast.Attribute) and isinstance(node.func.value, ast.Name) and node.func.value.id == "self":
                return self.ir.functions[node.func.attr].return_type
            canonical = self.canonical_name(node.func)
            if canonical == "numpy.argsort": return NativeType.list(NativeType.int())
            if isinstance(node.func, ast.Name):
                if node.func.id == "len": return NativeType.int()
                if node.func.id == "float": return NativeType.float()
                if node.func.id == "round":
                    return NativeType.int() if len(node.args) == 1 else NativeType.float()
                if node.func.id == "int": return NativeType.int()
                if node.func.id == "bool": return NativeType.bool()
                if node.func.id in {"min", "max", "abs"}:
                    types = [self.type_of(argument) for argument in node.args]
                    return NativeType.float() if NativeType.float() in set(types) else types[0]
            if canonical and canonical.startswith("math."):
                return NativeType.int() if canonical in {"math.floor", "math.ceil"} else NativeType.float()
            if isinstance(node.func, ast.Attribute):
                owner = self.type_of(node.func.value)
                if node.func.attr == "copy": return owner
                if node.func.attr == "append": return NativeType.none()
                if node.func.attr == "pop" and owner.item is not None: return owner.item
        raise AssertionError(f"unable to recover type for {ast.dump(node)}")

    def unique(self, stem: str) -> str:
        self._unique_counter += 1
        return f"__rko_{stem}_{self._unique_counter}"


def emit_problem_header(ir: EnvironmentIR) -> str:
    return CppEmitter(ir).render()


# ============================================================================
# Serialização de dados e empacotamento de artefatos (antigo api.py)
# ============================================================================

def _json_bytes(value: Any) -> bytes:
    return (json.dumps(value, indent=2, ensure_ascii=False, sort_keys=True) + "\n").encode("utf-8")


def _write_json(path: Path, value: Any) -> None:
    path.write_bytes(_json_bytes(value))


def _snapshot_tokens(value: Any, type_info: NativeType) -> list[str]:
    if type_info.kind == "list" and type_info.item is not None:
        tokens = [str(len(value))]
        for item in value:
            tokens.extend(_snapshot_tokens(item, type_info.item))
        return tokens
    if type_info.kind == "tuple":
        tokens: list[str] = []
        for item, item_type in zip(value, type_info.items):
            tokens.extend(_snapshot_tokens(item, item_type))
        return tokens
    if type_info.kind == "bool":
        return ["1" if value else "0"]
    if type_info.kind == "int64":
        return [str(value)]
    if type_info.kind == "float64":
        return [repr(float(value))]
    raise ValueError(f"cannot serialize V1 type {type_info.display()}")


def _instance_text(ir: EnvironmentIR) -> str:
    lines = ["RKO_NATIVE_DATA_V1"]
    for field in ir.data_fields:
        lines.append(" ".join(_snapshot_tokens(field.value, field.type)))
    return "\n".join(lines) + "\n"


def _schema_data(ir: EnvironmentIR) -> dict[str, Any]:
    return {
        "language_version": LANGUAGE_VERSION,
        "class_name": ir.class_name,
        "tam_solution": ir.tam_solution,
        "fields": [field.to_data(include_value=False) for field in ir.data_fields],
    }


def _providers_used(ir: EnvironmentIR) -> list[dict[str, Any]]:
    providers: dict[str, dict[str, Any]] = {
        "rko.native.builtins": {
            "name": "rko.native.builtins",
            "version": "1",
            "semantics": "RKO Native V1 finite numeric and container runtime",
        }
    }
    for function in ir.functions.values():
        for node in ast.walk(function.node):
            if isinstance(node, ast.Call):
                rendered = ast.unparse(node.func)
                if rendered.endswith("argsort"):
                    providers["numpy.argsort.stable.float64_1d"] = {
                        "name": "numpy.argsort.stable.float64_1d",
                        "version": "1",
                        "semantics": "finite float64, 1D, kind='stable'",
                    }
                if isinstance(node.func, ast.Name) and node.func.id == "round":
                    providers["python.round.float64.decimal"] = {
                        "name": "python.round.float64.decimal",
                        "version": "1",
                        "semantics": "finite float64, ties-to-even, non-negative constant ndigits",
                    }
                canonical = rendered
                if isinstance(node.func, ast.Name):
                    canonical = ir.import_aliases.get(node.func.id, rendered)
                if canonical.startswith("math."):
                    providers["rko.native.math"] = {
                        "name": "rko.native.math",
                        "version": "1",
                        "semantics": "finite float64 mapped to C++ standard math",
                    }
    return [providers[name] for name in sorted(providers)]


def analyze_environment(env: Any) -> dict[str, Any]:
    """Analyze an initialized environment and return a structured V1 report."""
    from .gera_tabela_simbolos import build_environment_ir
    try:
        ir = build_environment_ir(env)
    except NativeCompileError as error:
        return {
            "language_version": LANGUAGE_VERSION,
            "supported": False,
            "diagnostics": [error.diagnostic.to_data()],
        }
    return {
        "language_version": LANGUAGE_VERSION,
        "supported": True,
        "class_name": ir.class_name,
        "source_file": ir.source_file,
        "function_order": ir.function_order,
        "functions": {
            name: function.to_data() for name, function in sorted(ir.functions.items())
        },
        "data_schema": _schema_data(ir),
        "providers": _providers_used(ir),
        "diagnostics": [],
    }


def compile_environment(env: Any, output_directory: str | Path) -> CompilationArtifact:
    """Compile an initialized V1 environment into Problem.h and an instance snapshot."""
    from .gera_tabela_simbolos import build_environment_ir
    output = Path(output_directory).resolve()
    output.mkdir(parents=True, exist_ok=True)
    try:
        ir = build_environment_ir(env)
    except NativeCompileError as error:
        _write_json(
            output / "compile_report.json",
            {
                "language_version": LANGUAGE_VERSION,
                "supported": False,
                "diagnostics": [error.diagnostic.to_data()],
            },
        )
        raise

    typed_ir_data = ir.to_data()
    schema_data = _schema_data(ir)
    instance_text = _instance_text(ir)
    problem_header_text = emit_problem_header(ir)
    report_data = analyze_environment(env)

    source_path = output / "environment_source.py.txt"
    ast_path = output / "environment_ast.txt"
    typed_ir_path = output / "typed_ir.json"
    schema_path = output / "instance_schema.json"
    instance_path = output / "instance.rko-data"
    problem_path = output / "Problem.h"
    report_path = output / "compile_report.json"
    manifest_path = output / "manifest.json"

    source_path.write_text(ir.source_text, encoding="utf-8")
    source_tree = ast.parse(ir.source_text, filename=ir.source_file, type_comments=True)
    ast_path.write_text(ast.dump(source_tree, indent=2, include_attributes=True) + "\n", encoding="utf-8")
    _write_json(typed_ir_path, typed_ir_data)
    _write_json(schema_path, schema_data)
    instance_path.write_text(instance_text, encoding="utf-8", newline="\n")
    problem_path.write_text(problem_header_text, encoding="utf-8", newline="\n")
    _write_json(report_path, report_data)
    _write_json(
        manifest_path,
        {
            "language_version": LANGUAGE_VERSION,
            "class_name": ir.class_name,
            "source_file": ir.source_file,
            "source_sha256": sha256(ir.source_text.encode("utf-8")).hexdigest(),
            "typed_ir_sha256": sha256(_json_bytes(typed_ir_data)).hexdigest(),
            "schema_sha256": sha256(_json_bytes(schema_data)).hexdigest(),
            "instance_sha256": sha256(instance_text.encode("utf-8")).hexdigest(),
            "problem_header_sha256": sha256(problem_header_text.encode("utf-8")).hexdigest(),
        },
    )
    return CompilationArtifact(
        output_directory=output,
        problem_header=problem_path,
        instance_data=instance_path,
        schema=schema_path,
        typed_ir=typed_ir_path,
        report=report_path,
        environment_ir=ir,
    )
